# Generated by Django 4.1 on 2022-09-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
