# Generated by Django 4.1 on 2022-09-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0004_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(default="Not Yet", max_length=13),
        ),
    ]
